import type { Metadata } from 'next';
import { inter, poppins } from '@/config/fonts';
import './globals.css';
import { AuthContextProvider } from '@/providers/auth-provider';

export const metadata: Metadata = {
  title: 'FloodWatch',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${poppins.variable} bg-[#EAEAEA] antialiased min-h-screen`}
      >
        <AuthContextProvider>{children}</AuthContextProvider>
      </body>
    </html>
  );
}
